In [ ]:
## Numpy is a multidimenstional array library
# Using numpy over lists - numpy use fixed type, faster to read less bytes of memory, you dont have to do type checking when iterating thtough objects, uses contiguous memory, SIMD Vector Processing, Effective Cache Utilization
# List focuses on - Size, Reference Count, Object Type, Object Value

In [5]:
import numpy as np
a = np.array([1,3,5])
b = np.array([1,2,3])

print(a*b)

[ 1  6 15]


In [ ]:
# Applications of Numpy
# Mathematics, Plotting (Matplotlib)
# backend (Pandas, Digital Photography)
# Machine Learning

In [6]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b = np.array([
    [9.0, 8.0, 7.0], 
    [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
# Get the dimensions of the numpy array
print(a.ndim)
print(b.ndim)

1
2


In [13]:
# Getting the shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [15]:
# Get the type
print(a.dtype)
print(b.dtype)

int64
float64


In [17]:
# Specifying the datatype
a = np.array([1,2,3], dtype='int16')
print(a)
print(a.dtype)
print(a.shape)
print(a.ndim)

[1 2 3]
int16
(3,)
1


In [19]:
# Get size
print(a.itemsize)

2


In [20]:
a = np.array([1,2,3], dtype='int32')
print(a)
print(a.dtype)
print(a.shape)
print(a.ndim)

[1 2 3]
int32
(3,)
1


In [24]:
# Get total size
print(a.size)
print(a.itemsize)
print(a.nbytes)

print("\n")

# Get total size
print(b.size)
print(b.itemsize)
print(b.nbytes)

3
4
12


6
8
48


In [26]:
# Accessing/Changing specific elements, rows, columns, etc. 

a = np.array([
    [1,2,3,4,5,6,7],
    [8,9,10,11,12,13,14]
])

print(a.size)
print(a.shape)

14
(2, 7)


In [28]:
# Get a specific element [r,c]

print(a[1,5])
print(a[1,-2])

13
13


In [29]:
# Get a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [ ]:
# Get a specific column
print(a[:, 2])

[ 3 10]


In [31]:
# Getting a little more fancy [startindex:endindex:stepsize]

print(a[0, 1:6:2])

[2 4 6]


In [36]:
# changing the element
a[1,5] = 20
print(a[1,5])
print(a)
print("\n")

# third column to be all 5s
a[:,2] = 5
print(a)
print("\n")

# changing in through sequence
a[:,2] = [1,2]
print(a)
print("\n")

20
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]




In [42]:
# 3D example

b = np.array([
    [[1,2], [3,4]],
    [[5,6], [7,8]]
    ])

print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific element (work outside in)

print(b[0,1,1])
print(b[:,1,:])

4
[[3 4]
 [7 8]]


In [46]:
# replace

b[:,1,:] = [[9,9], [8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [47]:
# Initializing different types of arrays

# All 0s matrix
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [48]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [49]:
np.zeros((2,3,4,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [51]:
# All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [52]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [54]:
# Any other number
np.full((2,2),99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
# Any other number (full_like)
np.full(a.shape, 4) # you can just do with 'a' as well


array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [56]:
# intialize the array of random numbers

np.random.rand(4,2)

array([[0.20818078, 0.77244771],
       [0.13226349, 0.17541825],
       [0.4582865 , 0.35518703],
       [0.26121029, 0.20420865]])

In [57]:
np.random.rand(4,2,3)

array([[[0.35752967, 0.41858871, 0.77717516],
        [0.37316062, 0.55211186, 0.72754744]],

       [[0.70181266, 0.4026688 , 0.55799136],
        [0.43365984, 0.91878875, 0.21067777]],

       [[0.15825492, 0.85979678, 0.6880601 ],
        [0.0442644 , 0.24036072, 0.50109737]],

       [[0.29884044, 0.16131398, 0.23720469],
        [0.01826576, 0.31708139, 0.0892289 ]]])

In [58]:
# if you want to pass the shape of the variable

np.random.random_sample(a.shape)

array([[0.72483916, 0.58681899, 0.06178304, 0.46824127, 0.70136967,
        0.66168184, 0.49645574],
       [0.86668976, 0.49646042, 0.81810378, 0.05131739, 0.65644209,
        0.09167986, 0.16740426]])

In [59]:
# random integer values

np.random.randint(7)

1

In [60]:
np.random.randint(7, size=(3,3))

array([[5, 2, 0],
       [3, 0, 0],
       [5, 2, 2]])

In [61]:
np.random.randint(4,8, size=(3,3))

array([[6, 4, 7],
       [6, 6, 5],
       [6, 6, 4]])

In [63]:
np.random.randint(-4,8, size=(3,3))

array([[-4, -3,  6],
       [-4, -4,  5],
       [-3,  0, -3]])

In [ ]:
# Identity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
# Using repeat
arr = np.array([1,2,3])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [68]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [69]:
output = np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [70]:
z = np.zeros((3,3))
print(z)

z[1,1] = 9
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [72]:
output[1:4,1:4] = z # you can also use output[1:-1, 1:-1] = z
print(output) 

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [73]:
#  Be careful when copying arrays
a = np.array([1,2,3])
b = a
print(b)
b[0] = 100
print(b)
print(a)

[1 2 3]
[100   2   3]
[100   2   3]


In [74]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)

[100   2   3]


In [80]:
# Mathematics

a = np.array([1,2,3,4])
print(a)
print(a+2)
print(a*2)
print(a/2)
print(a**2)

[1 2 3 4]
[3 4 5 6]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [81]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [82]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [83]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [87]:
# Linear Algebra

a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [88]:
# finding the determinant
c = np.identity(3)
det = np.linalg.det(c)
print(det)

1.0


In [ ]:
# Determinant
# Trace
# Singular Value Decomposition
# Eigenvalues
# Matrix Normalization
# Inverse

In [92]:
# Statistics

stats = np.array([[1,2,3], [4,5,6]])
print(stats)
print(np.max(stats, axis=0)) # columms
print(np.max(stats, axis=1)) # rows

[[1 2 3]
 [4 5 6]]
[4 5 6]
[3 6]


In [93]:
np.sum(stats)

np.int64(21)

In [94]:
# add the terms in the columns
np.sum(stats, axis=0)

array([5, 7, 9])

In [95]:
# Reorganizing arrays

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [96]:
print(before.shape)

(2, 4)


In [97]:
after = before.reshape(8,1)
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [99]:
after2 = before.reshape((4,2))
print(after2)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [101]:
# Vertically stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1, v2]) # you can add more when you want


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [103]:
# Horizontal stack

h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [113]:
# Miscellaneous 
# Load data from a file

filedata = np.genfromtxt('data.txt', delimiter=",")
filedata.astype('int32')
print(filedata)

[[ 1.  2.  3.  4.  5.  6.  7.  8.]
 [ 9. 10. 11. 12. 13. 14. 15. 16.]
 [17. 18. 19. 20. 21. 22. 23. 24.]]


In [114]:
# Advanced Indexing

# Boolean Masking and Advanced Indexing

filedata > 50


array([[False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [115]:
filedata[filedata > 11]

array([12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24.])

In [116]:
# You can index with a list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [117]:
np.any(filedata > 11, axis=0)

array([ True,  True,  True,  True,  True,  True,  True,  True])

In [119]:
np.all(filedata > 11, axis=1)

array([False, False,  True])

In [122]:
((filedata > 11) & (filedata < 13))

array([[False, False, False, False, False, False, False, False],
       [False, False, False,  True, False, False, False, False],
       [False, False, False, False, False, False, False, False]])

In [123]:
~((filedata > 11) & (filedata < 13))

array([[ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])