In [ ]:
# Numpy
# Numerical and Vectorized Operations

# 1. Multidimensional Arrays
# 2. Slicing
# 3. Arithmetic
# 4. Broadcasting
# 5. Aggregate Functions
# 6. Filtering
# 7. Random Numbers

In [1]:
import numpy as np
print(np.__version__)

2.0.2


In [2]:
my_list = [1, 2, 3, 4]
print(my_list)

[1, 2, 3, 4]


In [3]:
array1 = np.array([1, 2, 3, 4])
print(array1)
print(type(array1))

[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
array1_mul = array1 * 2
print(array1_mul)

[2 4 6 8]


In [ ]:
###
# Multidimensional Array

In [10]:
# zero dimensional array
array2 = np.array('A')
print(array2)
print(array2.ndim)

A
0


In [11]:
# 1 dimensional array
array2 = np.array(['A', 'B', 'C'])
print(array2)
print(array2.ndim)

['A' 'B' 'C']
1


In [12]:
# 2 dimensional array
array2 = np.array([['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']])
print(array2)
print(array2.ndim)

[['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]
2


In [14]:
array3d = np.array([
                    [[1, 2, 3], [4, 5, 6]],
                    [[7, 8, 9], [10, 11, 12]],
                    [[13, 14, 15], [16, 17, 18]],
                    ])
print(array3d)
print(array3d.ndim)

# the number of values should exactly be the same
# if the values are missing you can use placeholders such as '' or _ or na

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]
3


In [16]:
# understanding the shape
print(array2.shape)
print(array3d.shape)

# tells you about the (depth, number of rows, number of columns)

(3, 3)
(3, 2, 3)


In [18]:
# use chain indexing to get the value from the array
# multidimensional indexing
print(array3d[0][0][1])
print(array3d[0, 0, 1])

2
2


In [20]:
array3d_alphabet = np.array([
                    [['A', 'B', 'C'], ['D', 'E', 'F'], ['G', 'H', 'I']],
                    [['J', 'K', 'L'], ['M', 'N', 'O'], ['P', 'Q', 'R']],
                    [['S', 'T', 'U'], ['V', 'W', 'X'], ['Y', 'Z', ' ']],
])

print(array3d_alphabet.ndim)
print(array3d_alphabet.shape)

3
(3, 3, 3)


In [23]:
word = array3d_alphabet[0, 0, 0]
print(word)

word = array3d_alphabet[0, 0, 0] + array3d_alphabet[2, 0, 1]
print(word)

A
AT


In [24]:
# Slicing

In [26]:
array4 = np.array([
              [1,2,3,4],
              [5,6,7,8],
              [9,10,11,12],
              [13,14,15,16]
              ])
print(array4)
print(array4.ndim)
print(array4.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
2
(4, 4)


In [27]:
# slicing -> subscript
# array[start:end:step]

In [29]:
print(array4[0]) # accessing row 0
print(array4[1]) # accessing row 1

# row selection

[1 2 3 4]
[5 6 7 8]


In [30]:
print(array4[0:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [32]:
print(array4[0:4:2])

# you can also write this as array4[::2]

[[ 1  2  3  4]
 [ 9 10 11 12]]


In [33]:
# reversing the order - row selection
print(array4[::-1])

[[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [34]:
# reversing the order - row selection
print(array4[::-2])

[[13 14 15 16]
 [ 5  6  7  8]]


In [35]:
# column selection
print(array4[:, 0:3])

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


In [36]:
# slicing - column selection
print(array4[:, 0::2])

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [37]:
# reversing the order - column selection
print(array4[:, ::-1])

[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [38]:
# reversing the order - column selection
print(array4[:, ::-2])

[[ 4  2]
 [ 8  6]
 [12 10]
 [16 14]]


In [39]:
# only taking first two rows and first two columns
# selecting a quadrant
print(array4[0:2, 0:2])

[[1 2]
 [5 6]]


In [40]:
# only taking first two rows and last two columns
# selecting a quadrant
print(array4[0:2, 2:])
# you can also write print(array4[0:2, 2:4])

[[3 4]
 [7 8]]


In [41]:
# only taking last two rows and last two columns
# selecting a quadrant
print(array4[2:, 2:])

[[11 12]
 [15 16]]


In [42]:
# Arithmetic

In [43]:
# Scalar Arithmetic

In [49]:
# Scalar arithmetic
array5 = np.array([1,2,3])
print(array5 + 1)
print(array5 - 2)
print(array5 * 3)
print(array5 / 4)
print(array5 ** 5)

[2 3 4]
[-1  0  1]
[3 6 9]
[0.25 0.5  0.75]
[  1  32 243]


In [50]:
# Vectorized maths functions
print(np.sqrt(array5))

[1.         1.41421356 1.73205081]


In [53]:
# rounding values
print(np.round(np.sqrt(array5)))
print(np.floor(np.sqrt(array5)))
print(np.ceil(np.sqrt(array5)))

[1. 1. 2.]
[1. 1. 1.]
[1. 2. 2.]


In [54]:
# built in constant
print(np.pi)

3.141592653589793


In [57]:
# Calculating the array
radius = np.array([1,2,3])
print((radius ** 2) * np.pi)

[ 3.14159265 12.56637061 28.27433388]


In [58]:
# Element wise arithmetic
array6 = np.array([1,2,3])
array7 = np.array([4,5,6])
print(array6 + array7)
print(array6 - array7)
print(array6 * array7)
print(array6 / array7)
print(array6 ** array7)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]


In [60]:
# comparison operators
scores = np.array([91, 55, 100, 73, 82, 64])

# returning a boolean array
print(scores >= 80)

[ True False  True False  True False]


In [61]:
# filtering
scores[scores < 60] = 0
print(scores)

[ 91   0 100  73  82  64]


In [62]:
# Boradcasting
# Broadcasting allows Numpy to perform operations on arrays with different shapes
# by virtually expanding dimensions so they match the larger array shapes

# The dimensions have the same size
# OR
# One of the dimensions have a size of 1

In [64]:
array8 = np.array([[1,2,3,4]])
array9 = np.array([[1], [2], [3], [4]])

print(array8.ndim)
print(array8.shape)

print("\n") # line break

print(array9.ndim)
print(array9.shape)

2
(1, 4)


2
(4, 1)


In [65]:
print(array8 * array9)

[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]
 [ 4  8 12 16]]


In [66]:
array8 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16],
])

In [67]:
print(array8 * array9)

[[ 1  2  3  4]
 [10 12 14 16]
 [27 30 33 36]
 [52 56 60 64]]


In [68]:
array8 = np.array([1,2,3,4,5,6,7,8,9,10])
array9 = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]])
print(array8.shape)
print(array9.shape)

(10,)
(10, 1)


In [69]:
print(array8 * array9)

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


In [70]:
# Aggregate functions
# Summarize data and typically return a single value


In [72]:
array10 = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
])

print(np.sum(array10))
print(np.mean(array10))
print(np.min(array10))
print(np.max(array10))
print(np.std(array10))
print(np.var(array10))

55
5.5
1
10
2.8722813232690143
8.25


In [74]:
# finding the position of minimum value
print(np.argmin(array10))
print(np.argmax(array10))

0
9


In [82]:
# scanning through columns
print(np.sum(array10, axis=0))

[ 7  9 11 13 15]


In [78]:
# Filtering
# Refers to process of selecting elements from an array that match a given condition

In [80]:
ages = np.array([
    [21,17,19,20,16,30,18,65],
    [39,22,15,99,18,19,20,21],
])

teenagers = ages[ages<18]

print(ages)
print("\n")
print(teenagers)

[[21 17 19 20 16 30 18 65]
 [39 22 15 99 18 19 20 21]]


[17 16 15]


In [81]:
adults = ages[(ages >= 18) & (ages < 65)]
print(adults)

[21 19 20 30 18 39 22 18 19 20 21]


In [83]:
# Random numbers

In [85]:
rng = np.random.default_rng()
print(rng.integers(1,7))

6


In [87]:
# if you want to get the same result you set a seed
rng = np.random.default_rng(seed=1)
print(rng.integers(low=1, high=101, size=(3,2)))

[[48 52]
 [76 96]
 [ 4 15]]


In [89]:
# setting the seed value
np.random.seed(seed=1)

print(np.random.uniform())
print("\n")
print(np.random.uniform(low=-1, high=1))
print("\n")
print(np.random.uniform(low=-1, high=1, size=(3,2)))

0.417022004702574


0.4406489868843162


[[-0.99977125 -0.39533485]
 [-0.70648822 -0.81532281]
 [-0.62747958 -0.30887855]]


In [90]:
# Shuffling the numbers from the array
rng = np.random.default_rng()
array11 = np.array([1,2,3,4,5])
rng.shuffle(array11)
print(array11)

[1 4 5 2 3]


In [94]:
# Selecting a random choice
random_choice = rng.choice(array11)
print(random_choice)

4


In [96]:
# having multiple random selections
random_choices = rng.choice(array11, size=3)
print(random_choices)

[2 2 3]
